# Generated by Django 5.1 on 2024-08-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author_name_book_book_type_book_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='books'),
        ),
    ]
